### ISSUE TITLE
False positive for yaml inline fields

### ISSUE THREAD

**Issue by abemedia** [tmzane/musttag#35]
The library `gopkg.in/yaml.v3` allows setting fields to behave as though they are embedded using the `inline` option, however `musttag` throws an error saying they should be annotated.

```go
type A struct {
	Foo string `yaml:"foo"`
}

type B struct {
	Embedded A `yaml:",inline"`
}

**Comment by junk1tm** [comment]
Hello,

Could you specify the version you are using?

I can't reproduce on `v0.5.0`
