### ISSUE TITLE
Do not complain about structs which implement json.Marshaler

### ISSUE THREAD

**Issue by mitar** [tmzane/musttag#64]
I have a struct which implements `json.Marshaler` interface by implementing `MarshalJSON` method on the struct, but this linter complains that I should define struct tags? Why? `MarshalJSON` does not need/use them.

**Comment by tmzane** [comment]
Good catch 👍

This corner case is indeed not covered at the moment.

**Comment by scop** [comment]
For completeness/maybe self evident, but unmarshaling should be handled similarly.

**Comment by tmzane** [comment]
I completely forgot about this one 😅 Will publish a fix in a few days.

**Comment by tmzane** [comment]
I've added support for all the interfaces from `json`, `xml`, `yaml` and `toml`, your case should be covered now.

Currently, it only works for the value semantics implementations (e.g. `func (Foo) MarshalJSON() ...`), I'm going to add pointer semantics support after I do some refactoring.

Thank you for the report!
